# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'SMT-SUB001 (aa748e82-e0df-42e3-ac20-f30b6a5077e0)'
    ScriptType: 'InlineScript'
    Inline: 'New-AzResourceGroup -Name test -Location "west europe"'